### ISSUE TITLE
The new Desktop icon looks like a bug

### ISSUE THREAD

**Issue by madsrh** [snwh/suru-icon-theme#74] opened 2018-07-01 11:31 UTC
This looks odd to me. To be honest I thought something went wrong here:

![image](https://user-images.githubusercontent.com/3986894/42133955-c318648a-7d32-11e8-8749-db991c7f886c.png)

**Comment by eaglersdeveloper** [comment] 2018-07-01 16:57
Fixed! 😄 

![desktop-fail](https://user-images.githubusercontent.com/40228953/42136245-cc205ad4-7d68-11e8-9736-b46371f87e8f.png)

If serious, then:
1. Design of this icon was in Humanity (probably, you know about this).
2. Sam isn't very much a perfectionist 🙃. For example, look at the [new Amazon icon](https://github.com/snwh/suru-icon-theme/issues/68#issuecomment-401079716).

**Comment by madsrh** [comment] 2018-07-01 18:13
> Fixed! 😄

Oh, the icons was supposed to look like the desktop??? 😨 Yes, the dock was missing, there isn't four workspaces by default, the wallpaper isn't purple 🤷‍♂️ 

> Sam isn't very much a perfectionist...

If this is sarcasm, I don't get it 😕 Unless you know a person really well, I would advise not to get personal online - the work is in focus here. Sams work is absolutely amazing. All I'm saying is that this icon looks out of place to me.

I apologize if my wording in the title come off as negative, but I'm 100% serious here.

**Comment by snwh** [comment] 2018-07-01 19:31
@madsrh this is as intended, it was a folder icon but folks complained that it was a folder (since the desktop icon shows up else where).

@eaglersdeveloper all the high resolution icons are different than those at the smaller resolution since the larger canvas area allows for having greater detail (Amazon one included). Also, you can take your unhelpful comments and remarks on my character elsewhere, they're not welcome here. 👋

**Comment by snwh** [comment] 2018-07-04 15:19
Closing because it's not a bug.

**Closed as completed by snwh** 2018-07-04 15:19 UTC
